# Generated by Django 4.1 on 2022-08-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registrosdiarios_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosdiarios',
            name='intervencao',
            field=models.CharField(blank=True, choices=[('HIDRO', 'Hidroginastica'), ('RELAX', 'Relaxamento'), ('PILTS', 'Pilates')], max_length=5),
        ),
    ]
