# Generated by Django 4.1 on 2022-08-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_alter_dadospessoais_exames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='intervencao1',
            field=models.CharField(blank=True, choices=[('HIDRO', 'Hidroginastica'), ('PILTS', 'Pilates')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='intervencao2',
            field=models.CharField(blank=True, choices=[('HIDRO', 'Hidroginastica'), ('PILTS', 'Pilates')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='turma1',
            field=models.CharField(blank=True, choices=[('TQ7h', 'Terca|Quinta|7h'), ('TQ8h', 'Terca|Quinta|8h'), ('QS7h', 'Quarta|Sexta|7h'), ('QS8h', 'Quarta|Sexta|8h'), ('PL7h', 'Pilates|7h'), ('PL8h', 'Pilates|8h')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='turma2',
            field=models.CharField(blank=True, choices=[('TQ7h', 'Terca|Quinta|7h'), ('TQ8h', 'Terca|Quinta|8h'), ('QS7h', 'Quarta|Sexta|7h'), ('QS8h', 'Quarta|Sexta|8h'), ('PL7h', 'Pilates|7h'), ('PL8h', 'Pilates|8h')], max_length=4, null=True),
        ),
    ]
